### ISSUE TITLE
ErrorWorkerProcess为何不启动

### ISSUE THREAD

**Issue by jovi-Li** [linzhiqiang/Aix.RedisStreamMessageBus#2]
await _processExecuter.AddProcess(new ErrorWorkerProcess(_serviceProvider), "redis失败任务处理");
注释掉了？

**Comment by linzhiqiang** [comment]
是的，现在在启动时会处理pel中的数据（由于服务停止，拉去了但是未消费的数据）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhiqiang/Aix.RedisStreamMessageBus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 中午1:05
收件人:&nbsp;"linzhiqiang/Aix.RedisStreamMessageBus"<Aix.RedisStreamMessageBus@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[linzhiqiang/Aix.RedisStreamMessageBus] ErrorWorkerProcess为何不启动 (#2)





 
await _processExecuter.AddProcess(new ErrorWorkerProcess(_serviceProvider), "redis失败任务处理");
 注释掉了？

**Comment by linzhiqiang** [comment]
在这里处理了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhiqiang/Aix.RedisStreamMessageBus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 中午1:05
收件人:&nbsp;"linzhiqiang/Aix.RedisStreamMessageBus"<Aix.RedisStreamMessageBus@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[linzhiqiang/Aix.RedisStreamMessageBus] ErrorWorkerProcess为何不启动 (#2)





 
await _processExecuter.AddProcess(new ErrorWorkerProcess(_serviceProvider), "redis失败任务处理");
 注释掉了？

**Comment by jovi-Li** [comment]
/// <summary>
        /// 服务启动时先处理pel中的数据（上次服务结束时拉去到但是未执行的数据/未ack）
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public async Task ProcessPel(BackgroundProcessContext context)
        {
            while (!context.IsShutdownRequested)
            {
                //读取pending 中的消息
                var list = await _database.StreamReadGroupAsync(_topic, _groupName, _consumerName, "0-0", 20);
                if (list == null || list.Length == 0)
                {
                    return;
                }

                await ProcessList(list, false);//每次启动时处理pel中的数据，要同步处理，等处理结束，再拉去新消息处理
            }
        }

这里读的不是pending的message 是new message

**Comment by jovi-Li** [comment]
另外我看消息处理异常也会ack ，然后是丢到发布订阅去处理 ？  发布订阅会丢失数据的啊 如果离线了

**Comment by linzhiqiang** [comment]
消息处理失败 会先插入延迟队列等待重试(再需要重试的情况下)，然后再ack




&nbsp;private async Task HandleWrap(StreamEntry streamEntry, JobData jobData)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; try
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await Handle(streamEntry, jobData);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; catch (Exception ex)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _logger.LogError(ex, $"RedisMessageBus消费失败,topic:{_topic}，groupName:{_groupName}");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; finally
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await _database.StreamAcknowledgeAsync(_topic, _groupName, streamEntry.Id);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; private async Task Handle(StreamEntry streamEntry, JobData jobData)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //JobData jobData = ParseJobData(streamEntry);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (jobData == null) return;


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (!string.IsNullOrEmpty(jobData.ErrorGroup) &amp;&amp; _groupName != jobData.ErrorGroup) //是出错的任务需要重试，但不是该组的不处理
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var isSuccess = await HandleMessage(jobData);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (!isSuccess &amp;&amp; jobData.ErrorCount < _options.MaxErrorReTryCount) //需要重试
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var delaySecond = GetDelaySecond(jobData.ErrorCount);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; jobData.ErrorCount++;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; jobData.ErrorGroup = _groupName;


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await _redisStorage.EnqueueDealy(jobData, TimeSpan.FromSeconds(delaySecond));
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _logger.LogInformation($"RedisMessageBus消费失败,topic:{jobData.Topic},{delaySecond}秒后将进行{jobData.ErrorCount }次重试");
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhiqiang/Aix.RedisStreamMessageBus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 下午2:45
收件人:&nbsp;"linzhiqiang/Aix.RedisStreamMessageBus"<Aix.RedisStreamMessageBus@noreply.github.com&gt;;
抄送:&nbsp;"林志强"<360779475@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhiqiang/Aix.RedisStreamMessageBus] ErrorWorkerProcess为何不启动 (#2)





 
另外我看消息处理异常也会ack ，然后是丢到发布订阅去处理 ？  发布订阅会丢失数据的啊 如果离线了

**Comment by linzhiqiang** [comment]
> 另外我看消息处理异常也会ack ，然后是丢到发布订阅去处理 ？ 发布订阅会丢失数据的啊 如果离线了

消息处理失败 会先插入延迟队列等待重试(再需要重试的情况下)，然后再ack

private async Task HandleWrap(StreamEntry streamEntry, JobData jobData)
        {
            try
            {
                await Handle(streamEntry, jobData);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"RedisMessageBus消费失败,topic:{_topic}，groupName:{_groupName}");
            }
            finally
            {
                await _database.StreamAcknowledgeAsync(_topic, _groupName, streamEntry.Id);
            }
        }

        private async Task Handle(StreamEntry streamEntry, JobData jobData)
        {
            //JobData jobData = ParseJobData(streamEntry);
            if (jobData == null) return;

            if (!string.IsNullOrEmpty(jobData.ErrorGroup) && _groupName != jobData.ErrorGroup) //是出错的任务需要重试，但不是该组的不处理
            {
                return;
            }
            var isSuccess = await HandleMessage(jobData);
            if (!isSuccess && jobData.ErrorCount < _options.MaxErrorReTryCount) //需要重试
            {
                var delaySecond = GetDelaySecond(jobData.ErrorCount);
                jobData.ErrorCount++;
                jobData.ErrorGroup = _groupName;

                await _redisStorage.EnqueueDealy(jobData, TimeSpan.FromSeconds(delaySecond));
                _logger.LogInformation($"RedisMessageBus消费失败,topic:{jobData.Topic},{delaySecond}秒后将进行{jobData.ErrorCount }次重试");
            }
        }

**Comment by linzhiqiang** [comment]
> ///
> 
> 
> /// 服务启动时先处理pel中的数据（上次服务结束时拉去到但是未执行的数据/未ack）
> ///
> 
> ///
> ///
> public async Task ProcessPel(BackgroundProcessContext context)
> {
> while (!context.IsShutdownRequested)
> {
> //读取pending 中的消息
> var list = await _database.StreamReadGroupAsync(_topic, _groupName, _consumerName, "0-0", 20);
> if (list == null || list.Length == 0)
> {
> return;
> }
> ```
>             await ProcessList(list, false);//每次启动时处理pel中的数据，要同步处理，等处理结束，再拉去新消息处理
>         }
>     }
> ```
> 
> 这里读的不是pending的message 是new message

这里读取的是当前消费者拉去过但是未ack的数据，就是上次关闭时未ack的消息，这里先处理完成之后，再开始循环拉去新消息处理

**Comment by jovi-Li** [comment]
> > ///
> > /// 服务启动时先处理pel中的数据（上次服务结束时拉去到但是未执行的数据/未ack）
> > ///
> > ///
> > ///
> > public async Task ProcessPel(BackgroundProcessContext context)
> > {
> > while (!context.IsShutdownRequested)
> > {
> > //读取pending 中的消息
> > var list = await _database.StreamReadGroupAsync(_topic, _groupName, _consumerName, "0-0", 20);
> > if (list == null || list.Length == 0)
> > {
> > return;
> > }
> > ```
> >             await ProcessList(list, false);//每次启动时处理pel中的数据，要同步处理，等处理结束，再拉去新消息处理
> >         }
> >     }
> > ```
> > 
> > 
> > 这里读的不是pending的message 是new message
> 
> 这里读取的是当前消费者拉去过但是未ack的数据，就是上次关闭时未ack的消息，这里先处理完成之后，再开始循环拉去新消息处理

拉过的消息不是应该在pending里面啊 ，应该是调用这个StreamPendingMessagesAsync方法把？

**Comment by jovi-Li** [comment]
> > 另外我看消息处理异常也会ack ，然后是丢到发布订阅去处理 ？ 发布订阅会丢失数据的啊 如果离线了
> 
> 消息处理失败 会先插入延迟队列等待重试(再需要重试的情况下)，然后再ack
> 
> private async Task HandleWrap(StreamEntry streamEntry, JobData jobData)
> {
> try
> {
> await Handle(streamEntry, jobData);
> }
> catch (Exception ex)
> {
> _logger.LogError(ex, $"RedisMessageBus消费失败,topic:{_topic}，groupName:{_groupName}");
> }
> finally
> {
> await _database.StreamAcknowledgeAsync(_topic, _groupName, streamEntry.Id);
> }
> }
> 
> ```
>     private async Task Handle(StreamEntry streamEntry, JobData jobData)
>     {
>         //JobData jobData = ParseJobData(streamEntry);
>         if (jobData == null) return;
> 
>         if (!string.IsNullOrEmpty(jobData.ErrorGroup) && _groupName != jobData.ErrorGroup) //是出错的任务需要重试，但不是该组的不处理
>         {
>             return;
>         }
>         var isSuccess = await HandleMessage(jobData);
>         if (!isSuccess && jobData.ErrorCount < _options.MaxErrorReTryCount) //需要重试
>         {
>             var delaySecond = GetDelaySecond(jobData.ErrorCount);
>             jobData.ErrorCount++;
>             jobData.ErrorGroup = _groupName;
> 
>             await _redisStorage.EnqueueDealy(jobData, TimeSpan.FromSeconds(delaySecond));
>             _logger.LogInformation($"RedisMessageBus消费失败,topic:{jobData.Topic},{delaySecond}秒后将进行{jobData.ErrorCount }次重试");
>         }
>     }
> ```

我没看清楚  谢谢 这个明白了

**Comment by linzhiqiang** [comment]
> > > ///
> > > /// 服务启动时先处理pel中的数据（上次服务结束时拉去到但是未执行的数据/未ack）
> > > ///
> > > ///
> > > ///
> > > public async Task ProcessPel(BackgroundProcessContext context)
> > > {
> > > while (!context.IsShutdownRequested)
> > > {
> > > //读取pending 中的消息
> > > var list = await _database.StreamReadGroupAsync(_topic, _groupName, _consumerName, "0-0", 20);
> > > if (list == null || list.Length == 0)
> > > {
> > > return;
> > > }
> > > ```
> > >             await ProcessList(list, false);//每次启动时处理pel中的数据，要同步处理，等处理结束，再拉去新消息处理
> > >         }
> > >     }
> > > ```
> > > 
> > > 
> > > 这里读的不是pending的message 是new message
> > 
> > 
> > 这里读取的是当前消费者拉去过但是未ack的数据，就是上次关闭时未ack的消息，这里先处理完成之后，再开始循环拉去新消息处理
> 
> 拉过的消息不是应该在pending里面啊 ，应该是调用这个StreamPendingMessagesAsync方法把？

这里拉取的是当前消费者拉取过但是未ack的数据，启动时执行一次，然后循环处理新的消息。看下下面的文档:

 What will happen if we crash in the middle of processing messages, is that our messages will remain in the pending entries list, so we can access our history by giving XREADGROUP initially an ID of 0, and performing the same loop. Once providing and ID of 0 the reply is an empty set of messages, we know that we processed and acknowledged all the pending messages: we can start to use > as ID, in order to get the new messages and rejoin the consumers that are processing new things.

**Comment by linzhiqiang** [comment]
> > > > ///
> > > > /// 服务启动时先处理pel中的数据（上次服务结束时拉去到但是未执行的数据/未ack）
> > > > ///
> > > > ///
> > > > ///
> > > > public async Task ProcessPel(BackgroundProcessContext context)
> > > > {
> > > > while (!context.IsShutdownRequested)
> > > > {
> > > > //读取pending 中的消息
> > > > var list = await _database.StreamReadGroupAsync(_topic, _groupName, _consumerName, "0-0", 20);
> > > > if (list == null || list.Length == 0)
> > > > {
> > > > return;
> > > > }
> > > > ```
> > > >             await ProcessList(list, false);//每次启动时处理pel中的数据，要同步处理，等处理结束，再拉去新消息处理
> > > >         }
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > > 这里读的不是pending的message 是new message
> > > 
> > > 
> > > 这里读取的是当前消费者拉去过但是未ack的数据，就是上次关闭时未ack的消息，这里先处理完成之后，再开始循环拉去新消息处理
> > 
> > 
> > 拉过的消息不是应该在pending里面啊 ，应该是调用这个StreamPendingMessagesAsync方法把？
> 
> 这里拉取的是当前消费者拉取过但是未ack的数据，启动时执行一次，然后循环处理新的消息。看下下面的文档:
> 
> What will happen if we crash in the middle of processing messages, is that our messages will remain in the pending entries list, so we can access our history by giving XREADGROUP initially an ID of 0, and performing the same loop. Once providing and ID of 0 the reply is an empty set of messages, we know that we processed and acknowledged all the pending messages: we can start to use > as ID, in order to get the new messages and rejoin the consumers that are processing new things.

StreamPendingMessagesAsync 这个方法时拉取一个组下的所有消费者的pel数据

**Comment by jovi-Li** [comment]
学习了 谢谢
